const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');
const root=path.resolve(__dirname,'..'),s=fs.readFileSync(path.join(root,'website/game.html'),'utf8');
const flinch=s.match(/const BOSS_FLINCH_VIDEOS = \{[\s\S]*?(?=const BOSS_INTRO_VIDEOS)/)[0];
const outro=s.match(/const BOSS_OUTRO_VIDEOS = \{[\s\S]*?(?=\/\/ ── Video bosses:)/)[0];
function setup({off=false,rejections=0,missing=null}={}) {
 let callbacks=0,plays=0,nextTimer=0;const timers=new Map(),sources=[],ducks=[];
 function element(){const attrs={};const classes=new Set();return {classList:{add(...a){a.forEach(x=>classes.add(x))},remove(...a){a.forEach(x=>classes.delete(x))},contains(x){return classes.has(x)}},style:{},setAttribute(k,v){attrs[k]=v;if(k==='src')sources.push(v)},getAttribute:k=>attrs[k]??null,removeAttribute:k=>delete attrs[k],load(){},pause(){},play(){plays++;return plays<=rejections?Promise.reject(Error('blocked')):Promise.resolve()},offsetWidth:1};}
 const elements=Object.fromEntries(['bfFlinchScene','bfFlinchVideo','bfPortalScene','bfIntroVideo','bfIntroTitle','bfIntroTap'].map(k=>[k,element()]));if(missing)delete elements[missing];
 const c=vm.createContext({document:{getElementById:id=>elements[id]||null},localStorage:{getItem:()=>off?'off':null},GameMusic:{duckTo:(...a)=>ducks.push(a)},setTimeout:(fn,ms)=>{const id=++nextTimer;timers.set(id,{fn,ms});return id},clearTimeout:id=>timers.delete(id)});
 vm.runInContext(flinch+outro,c);
 return {c,elements,sources,ducks,timers,done:()=>callbacks++,get calls(){return callbacks},get plays(){return plays},run(ms){for(const [id,t] of [...timers])if(t.ms===ms){timers.delete(id);t.fn()}}};
}
const cases=[];async function test(name,fn){await fn();cases.push(name)}const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{
 await test('all11 Guardians have4 ordered flinches and1 defeat; Gambler Journal preserved',()=>{const t=setup();for(let g=1;g<=11;g++){assert.equal(vm.runInContext(`BOSS_FLINCH_VIDEOS[${g}].length`,t.c),4);for(let n=1;n<=4;n++)assert.equal(vm.runInContext(`BOSS_FLINCH_VIDEOS[${g}][${n-1}]`,t.c),`bosses/flinches/boss-${g}-flinch-${n}.mp4`);assert.equal(vm.runInContext(`BOSS_OUTRO_VIDEOS[${g}][0]`,t.c),`bosses/outros/boss-${g}-defeat.mp4`)}assert.equal(vm.runInContext('BOSS_OUTRO_VIDEOS[1][1]',t.c),'bosses/outros/finn-journal.mp4')});
 for(const exit of ['ended','error','skip','timeout'])await test('flinch '+exit+' returns once and restores music',()=>{const t=setup();t.c.playBossFlinch(11,4,t.done);const saved=t.elements.bfFlinchVideo.onended;if(exit==='ended')saved();if(exit==='error')t.elements.bfFlinchVideo.onerror();if(exit==='skip')t.elements.bfFlinchScene.onclick();if(exit==='timeout')t.run(9000);saved();assert.equal(t.calls,1);assert.equal(t.ducks.at(-1)[0],1);t.run(280);assert.equal(t.elements.bfFlinchVideo.getAttribute('src'),null);assert(!t.elements.bfFlinchScene.classList.contains('on'))});
 for(const missing of ['bfFlinchScene','bfFlinchVideo'])await test('missing '+missing+' cannot hang',()=>{const t=setup({missing});t.c.playBossFlinch(1,1,t.done);t.run(280);assert.equal(t.calls,1)});
 await test('unmapped Guardian returns without playing',()=>{const t=setup();t.c.playBossFlinch(99,1,t.done);assert.equal(t.calls,1);assert.equal(t.plays,0)});
 await test('audible autoplay refusal retries muted and keeps cinematic',async()=>{const t=setup({rejections:1});t.c.playBossFlinch(2,1,t.done);await tick();assert.equal(t.plays,2);assert(t.elements.bfFlinchVideo.muted);assert.equal(t.calls,0);t.elements.bfFlinchVideo.onended();assert.equal(t.calls,1)});
 await test('double autoplay refusal returns once',async()=>{const t=setup({rejections:2});t.c.playBossFlinch(2,1,t.done);await tick();assert.equal(t.calls,1)});
 await test('audio preference controls native track',()=>{for(const off of [true,false]){const t=setup({off});t.c.playBossFlinch(3,1,t.done);assert.equal(t.elements.bfFlinchVideo.muted,off)}});
 await test('delayed cleanup does not erase a repeated same-source clip',()=>{const t=setup();t.c.playBossFlinch(6,4,t.done);t.elements.bfFlinchVideo.onended();t.c.playBossFlinch(6,4,t.done);t.run(280);assert.equal(t.elements.bfFlinchVideo.getAttribute('src'),'bosses/flinches/boss-6-flinch-4.mp4')});
 await test('first Gambler defeat then Journal, exactly once',()=>{const t=setup();t.c.playBossOutroCinematic(1,t.done);const old=t.elements.bfIntroVideo.onended;old();old();assert.deepEqual(t.sources,['bosses/outros/boss-1-defeat.mp4','bosses/outros/finn-journal.mp4']);assert(t.elements.bfIntroVideo.muted);t.elements.bfIntroVideo.onended();assert.equal(t.calls,1);assert.equal(t.elements.bfIntroTitle.style.display,'')});
 await test('repeat Gambler victory omits Journal',()=>{const t=setup();t.c.playBossOutroCinematic(1,t.done,{includeJournal:false});t.elements.bfIntroVideo.onended();assert.deepEqual(t.sources,['bosses/outros/boss-1-defeat.mp4']);assert.equal(t.calls,1)});
 for(const exit of ['ended','error','skip','timeout'])await test('all other Guardian defeats '+exit+' cannot block rewards',()=>{for(let g=2;g<=11;g++){const t=setup();t.c.playBossOutroCinematic(g,t.done);if(exit==='ended')t.elements.bfIntroVideo.onended();if(exit==='error')t.elements.bfIntroVideo.onerror();if(exit==='skip')t.elements.bfPortalScene.onclick();if(exit==='timeout')t.run(20000);assert.equal(t.calls,1);assert.equal(t.ducks.at(-1)[0],1)}});
 await test('outro audible refusal falls back muted',async()=>{const t=setup({rejections:1});t.c.playBossOutroCinematic(11,t.done);await tick();assert.equal(t.plays,2);assert(t.elements.bfIntroVideo.muted);assert.equal(t.calls,0);t.elements.bfIntroVideo.onended();assert.equal(t.calls,1)});
 await test('outro double refusal restores controls',async()=>{const t=setup({rejections:2});t.c.playBossOutroCinematic(11,t.done);await tick();assert.equal(t.calls,1);assert.equal(t.elements.bfIntroTap.style.display,'')});
 await test('damage intensity reaches stun for4 or5 HP; wrong/fatal hits do not flinch',()=>{const expr=s.match(/const _flinchN = ([\s\S]*?);/)[1];const select=new Function('passed','bfState','BOSS_FLINCH_VIDEOS','return '+expr);const map={4:[1,2,3,4]};assert.deepEqual([4,3,2,1].map(hp=>select(true,{level:4,bossHP:hp,maxBossHP:5},map)),[1,2,3,4]);assert.deepEqual([3,2,1].map(hp=>select(true,{level:4,bossHP:hp,maxBossHP:4},map)),[1,3,4]);assert.equal(select(false,{level:4,bossHP:3,maxBossHP:4},map),0);assert.equal(select(true,{level:4,bossHP:0,maxBossHP:4},map),0)});
 await test('bossWin routes non-Gambler defeat before Eel glasses',()=>{assert(s.includes('playBossOutroCinematic(level, afterDefeat, { includeJournal: false })'));assert(s.includes('const unlockGlasses = level === 2 && bfState._firstEverKill !== false;'));assert(s.includes('if (isGambler && (bfState._firstEverKill !== false || _journalQuestPending))'))});
 fs.writeFileSync(path.join(root,'.chartquest/qa/guardian-player-test-results.json'),JSON.stringify({status:'PASS',count:cases.length,cases},null,2));console.log(`${cases.length} meaningful player/mapping tests PASS`);
})().catch(e=>{console.error(e);process.exit(1)});
