/* ChartQuest — service worker (asset cache + installability).
 *
 * IMPORTANT: page navigations are intentionally NOT intercepted.
 * Cloudflare Pages serves clean URLs (/play.html -> 308 -> /play). A service
 * worker must never return a *redirected* response for a navigation — the
 * browser rejects it with ERR_FAILED ("This site can't be reached"). Letting
 * the browser handle HTML navigation (and its redirects) natively avoids that
 * entire class of bug for /play, /bosses, /courses, etc.
 */
/* BUMP THIS IN THE SAME COMMIT AS ANY CHANGE TO A PRECACHED OR RUNTIME-CACHED ASSET.
   Static assets below are cache-first with NO revalidation, so a returning tester keeps the
   old copy until this string changes. v8: config.js now gates the courses page off and
   site.js drops the fake signup form — without a bump, anyone who had visited before would
   have kept the old pair and still seen both.
   v9: site.js again — it no longer animates the invisible #cqnet canvas behind the game on
   the play page. That IS the desktop lag fix, so it must actually reach returning testers.
   v10: the tracker itself changed (one session per visit, durable retry, build tag). cq-track.js
   is now precached EXPLICITLY rather than only runtime-cached, so it is unambiguously versioned.
   v12: repairing this comment. v10's text was appended AFTER the block's closing delimiter, so
   from build 332 until now this file was a SyntaxError and the service worker never registered
   at all — no precache, no offline page, and a console error on every load. */
/* BUMP THIS ON ANY CHANGE TO A PRECACHED FILE — assets/cq-track.js ESPECIALLY.
   v12 → v13 (2026-08-05): build 343 added play_clicked + movement_tutorial_completed to
   cq-track.js, but this version string did not move. The activate handler only purges caches
   whose key differs from CACHE, so every returning visitor kept being served the v12 copy of
   cq-track.js — 21,642 bytes, no new event names — while the network copy was 32,916 bytes.
   CQTrack.event('play_clicked') simply returned false for them and the two stages recorded
   NOTHING. Caught live, by testing the emit path in a browser that had visited before; a fresh
   browser works fine, which is exactly why this class of bug survives local checking.
   The precache list is not "just marketing assets" — it contains the ANALYTICS CLIENT. */
const CACHE = 'chartquest-site-v13';
const OFFLINE_URL = './offline.html';
const ASSETS = [
  './',
  OFFLINE_URL,
  './assets/site.css', './assets/site.js', './assets/config.js', './assets/cq-track.js',
  './assets/chartquest-poster.jpg', './manifest.webmanifest',
  './assets/pwa/icon-192.png', './assets/pwa/icon-512.png', './assets/pwa/icon-180.png'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS).catch(() => {})).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  // Drop every old cache (incl. the broken v2 that cached the redirected play.html).
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;

  // Page/iframe navigations. While ONLINE we still do not intercept at all, so the
  // browser follows Cloudflare's clean-URL 308s natively and we can never hand it a
  // *redirected* response (that returns ERR_FAILED and once broke the Play button).
  // Only when the device is offline do we take over, purely to serve offline.html.
  if (req.mode === 'navigate') {
    if (!self.navigator.onLine) {
      e.respondWith(caches.match(OFFLINE_URL).then(hit => {
        if (!hit) return fetch(req);
        // Rebuild the response so `.redirected` is false. On Cloudflare, ./offline.html
        // 308s to /offline, so `addAll` stored a REDIRECTED response — and a SW may not
        // hand a redirected response to a navigation (ERR_FAILED). Reconstructing from
        // the body strips that flag; harmless when the cached entry wasn't redirected.
        return hit.blob().then(body => new Response(body, {
          status: 200, headers: { 'Content-Type': 'text/html; charset=utf-8' }
        }));
      }));
    }
    return;
  }

  // The live game needs fresh market data. So does the homepage OHLC snapshot —
  // it is regenerated by scripts/fetch_markets.py, so it must never be pinned
  // cache-first (the vendored chart lib is immutable and stays cache-first).
  if (req.url.includes('game.html') || req.url.includes('market-data.js')) {
    e.respondWith(fetch(req).catch(() => caches.match(req)));
    return;
  }

  // Static assets: cache-first; only cache clean (ok, non-redirected) responses.
  e.respondWith(
    caches.match(req).then(hit => hit || fetch(req).then(res => {
      if (res && res.ok && !res.redirected) {
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
      }
      return res;
    }).catch(() => undefined))
  );
});
